export function Subscription() {
  return [
    {
      title: "Amateur",
      image: "/botin1.svg",
      slogan: "Construi tu carrera",
      features: [
        { text: "Página de perfil", available: true },
        { text: "Aplica a ofertas", available: false },
        { text: "Accede a cursos con descuento", available: false },
        { text: "Accede a entrenamientos con descuento", available: false },
        { text: "Perfil Destacado", available: false },
      ],
      monthlyPrice: "GRATIS",
      buttonLabel: "Registrate Gratis",
      bgColor: "bg-white",
      textColor: "text-gray-800",
      borderColor: "border-gray-300",
      buttonColor: "bg-verde-oscuro",
      priceId: { monthly: null, yearly: null }, 
    },
    {
      title: "Semiprofesional",
      image: "/botin2.svg",
      slogan: "Sé parte del juego activo",
      features: [
        { text: "Página de perfil", available: true },
        { text: "Ofertas estándar", available: true },
        { text: "Accede a cursos con descuento", available: true },
        { text: "Accede a entrenamientos con descuento", available: false },
        { text: "Perfil Destacado", available: false },
      ],
      monthlyPrice: "€3,95",
      yearlyPrice: "€37,95 Anual (-20%)",
      buttonLabel: "Contratar", 
      bgColor: "bg-white",
      textColor: "text-gray-800",
      borderColor: "border-verde-claro",
      buttonColor: "bg-verde-claro",
      priceId: {
        monthly: "price_1R7MPlGbCHvHfqXFNjW8oj2k",
        yearly: "price_1R7MPlGbCHvHfqXFapD8MeOw",
      },
    },
    {
      title: "Profesional",
      image: "/botin3.svg",
      slogan: "Destaca en el mercado profesional",
      features: [
        { text: "Página de perfil", available: true },
        { text: "Ofertas Internacionales", available: true },
        { text: "Accede a cursos con descuento", available: true },
        { text: "Accede a entrenamientos con descuento", available: true },
        { text: "Perfil Destacado", available: true },
      ],
      monthlyPrice: "€7,95",
      yearlyPrice: "€75,95 Anual (-20%)",
      buttonLabel: "Contratar",
      bgColor: "bg-white",
      textColor: "text-gray-800",
      borderColor: "border-verde-oscuro",
      buttonColor: "bg-verde-oscuro",
      priceId: {
        monthly: "price_1R7MaqGbCHvHfqXFimcCzvlo",
        yearly: "price_1R7MbgGbCHvHfqXFYECGw8S9",
      },
    },
  ];
}
