export const positionOptions = [
  "Jugador",
  "Entrenador",
  "Fisioterapeuta",
  "Gerente",
  "Preparador Físico",
  "Analista",
  "Coordinador",
  "Entrenador de Porteros",
  "Marketing Digital",
  "Ojeador Scout",
  "Director Deportivo",
  "Comercial",
  "Jefe de Reclutamiento",
  "Periodista",
  "Diseñador Gráfico",
  "Administrativo",
  "Nutricionista",
  "Director Ejecutivo",
  "Director Técnico",
  "Psicólogo",
  "Editor Multimedia",
  "Médico",
  "Recursos Humanos",
  "Abogado",
  "Científico Deportivo",
  "Director de Negocio",
  "Finanzas",
  "Delegado",
  "Profesor",
  "Árbitro",
  "Ejecutivo",
  "Inversor",
  "Representante",
  "Utillero",
  "Agente",
  "Masajista",
  "Terapeuta",
];
